package com.example.bitlinker.translator.sqllitedb;

import com.example.bitlinker.translator.model.TranslatedText;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteColumn;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteType;

/**
 * Created by bitlinker on 20.08.2016.
 */

@StorIOSQLiteType(table = TranslationsTable.TABLE)
public class TranslatedTextEntry {
    @StorIOSQLiteColumn(name = TranslationsTable.COLUMN_ID, key = true)
    Long id;

    @StorIOSQLiteColumn(name = TranslationsTable.COLUMN_ORIGINAL_TEXT)
    String mOriginalText;

    @StorIOSQLiteColumn(name = TranslationsTable.COLUMN_TRANSLATED_TEXT)
    String mTranslatedText;

    @StorIOSQLiteColumn(name = TranslationsTable.COLUMN_LANGUAGE)
    String mLanguage;

    // leave default constructor for AutoGenerated code!
    TranslatedTextEntry() {
    }

    public static TranslatedTextEntry fromTranslatedText(TranslatedText text) {
        TranslatedTextEntry entry = new TranslatedTextEntry();
        entry.mOriginalText = text.getOriginalText();
        entry.mTranslatedText = text.getTranslatedText();
        entry.mLanguage = text.getLanguage();
        return entry;
    }
}
